FROM python:3.9  
WORKDIR /code
COPY ./package.json /code/package.json
RUN pip install --no-cache-dir --upgrade -r /code/package.json
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "80"]
